baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tom E. Hardwicke"
theme = "ezhil"
paginate = 5

copyright = ""

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

summaryLength = 20

[params]
	subtitle = "Marie Skłodowska-Curie Research Fellow"
	subtitle2 = "Department of Psychology"
	subtitle3 = "University of Amsterdam"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "light" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 1

[[menu.main]]
name = "CV"
url = "files/Hardwicke_cv.pdf"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/tomhardwicke/"

[taxonomies]
   tag = "tags"
